apiVersion: apps/v1
kind: Deployment
metadata:
  name: relayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relayer
  template:
    metadata:
      labels:
        app: relayer
    spec:
      containers:
        - name: relayer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8899
          env:
            {{- toYaml .Values.env | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: relayer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: relayer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8899


