name: Relayer Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/relayer
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.RELAYER_REGISTRY }}
          username: ${{ secrets.RELAYER_REGISTRY_USERNAME }}
          password: ${{ secrets.RELAYER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: packages/relayer
          file: packages/relayer/Dockerfile
          push: true
          tags: ${{ secrets.RELAYER_REGISTRY }}/${{ secrets.RELAYER_IMAGE_NAME }}:${{ inputs.image_tag }}


